# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Determine whether a function belongs to a special type
#' @description C++ prototype function of \link{BoolFun_Type}.
#' @param boolfuns [\code{LogicalVector}] the Boolean function logical vector.
#' @param k [\code{int}] the number of input variables of the function.
#' @param Type [\code{char}] function type.
#' @param Showit [\code{bool}] whether show the function?
c_BF_isPointed <- function(boolfuns, k, Type, Showit) {
    .Call(`_BioLogical_c_BF_isPointed`, boolfuns, k, Type, Showit)
}

#' @title Generate a specific type of Boolean function
#' @description C++ prototype function of \link{BoolFun_Generator}.
#' @param Type [\code{char}] function type.
#' @param k [\code{k}] the number of input variables of the function.
#' @param bias [\code{double}] function bias.
#' @param Vars [\code{IntegerVector}] some configuration parameters.
c_BF_Generator <- function(Type, k, bias, Vars) {
    .Call(`_BioLogical_c_BF_Generator`, Type, k, bias, Vars)
}

#' @title Calculate the sensitivity of a Boolean function
#' @description C++ prototype function of \link{BoolFun_Sensitivity}.
#' @param boolfuns [\code{LogicalVector &}] the Boolean function logical vector.
#' @param k [\code{int}] the number of input variables of the function.
c_BF_Sensitivity <- function(boolfuns, k) {
    .Call(`_BioLogical_c_BF_Sensitivity`, boolfuns, k)
}

#' @title Calculate the effective edges of a Boolean function
#' @description C++ prototype function of \link{BoolFun_Effectiveness}.
#' @param boolfuns [\code{IntegerVector &}] the Boolean function.
#' @param k [\code{int}] the number of input variables of the function.
c_BF_Effective <- function(boolfuns, k) {
    .Call(`_BioLogical_c_BF_Effective`, boolfuns, k)
}

#' @title Calculate the complexity of a Boolean function
#' @description C++ prototype function of \link{BoolFun_Complexity}.
#' @param boolfuns [\code{IntegerVector &}] the Boolean function.
#' @param k [\code{int}] the number of input variables of the function.
c_BF_Complexity <- function(boolfuns, k) {
    .Call(`_BioLogical_c_BF_Complexity`, boolfuns, k)
}

#' @title Calculate the effective edges of a Boolean function
#' @description C++ prototype function of \link{BoolFun_Effectiveness}.
#' @param boolfuns [\code{IntegerVector &}] the Boolean function.
#' @param k [\code{int}] the number of input variables of the function.
c_BF_EffectiveEdges <- function(boolfuns, k) {
    .Call(`_BioLogical_c_BF_EffectiveEdges`, boolfuns, k)
}

#' @title Display the Quine-McCluskey form of a Boolean function
#' @description C++ prototype function of \link{BoolFun_QMForm}.
#' @param boolfuns [\code{IntegerVector &}] the Boolean function.
#' @param k [\code{int}] the number of input variables of the function.
#' @param VarsName [\code{CharacterVector}] variable names.
c_BF_QuineMcCluskey <- function(boolfuns, k, VarsName) {
    invisible(.Call(`_BioLogical_c_BF_QuineMcCluskey`, boolfuns, k, VarsName))
}

#' @title Enumerate all possible input vectors
#' @description C++ prototype function for enumerate all possible input vectors
#' under the given length.
#' @param VarNum [\code{int}] the number of input variables of the function
c_FrameTruthTable <- function(VarNum) {
    .Call(`_BioLogical_c_FrameTruthTable`, VarNum)
}

#' @title Decode the structure of a nested canalized Boolean function
#' @description C++ prototype function of \link{BoolFun_NestedCana}.
#' @param boolfuns [\code{IntegerVector &}] the Boolean function logical vector.
#' @param k [\code{int}] the number of input variables of the function.
c_B_NestedCanalized <- function(boolfuns, k) {
    .Call(`_BioLogical_c_B_NestedCanalized`, boolfuns, k)
}

#' @title Analyze damage spread within system
#' @description C++ prototype function of \link{DNS_DamageSpread}
#' @param sys_size [\code{int}] system size
#' @param ll_system [\code{int}] level number of discrete system
#' @param sim_step [\code{int}] simulating steps
#' @param obf_type [\code{char}] ordered Boolean function type
#' @param bias_rf [\code{NumericVector}] bias in random function 
#' @param obf_ratio [\code{double}] proportion of ordered Boolean function 
#' @param init_dis [\code{double}] initial normalized Hamming distance
#' @param init_1_ratio [\code{NumericVector}] "1" proportion of initial state
#' @param net_type [\code{char}] system topological type
#' @param net_f_para [\code{double}] topological configured parameters
#' @param obf_i_para1 [\code{int}] configuration parameter for OBF (1)
#' @param obf_i_para2 [\code{int}] configuration parameter for OBF (2)
#' @param RuleType [\code{int}] update strategy
c_Derrida_Simualtion <- function(sys_size, ll_system, sim_step, obf_type, bias_rf, obf_ratio, init_dis, init_1_ratio, net_type, net_f_para, obf_i_para1, obf_i_para2, RuleType) {
    .Call(`_BioLogical_c_Derrida_Simualtion`, sys_size, ll_system, sim_step, obf_type, bias_rf, obf_ratio, init_dis, init_1_ratio, net_type, net_f_para, obf_i_para1, obf_i_para2, RuleType)
}

c_Derrida_Load <- function(aRealNet, PointedGene, PointValues, InD, OtD, init_dis, init_1_ratio, sim_step, RuleType) {
    .Call(`_BioLogical_c_Derrida_Load`, aRealNet, PointedGene, PointValues, InD, OtD, init_dis, init_1_ratio, sim_step, RuleType)
}

#' @title Analyze percolation within system
#' @description C++ prototype function of \link{DNS_Percolation}
#' @param sys_size [\code{int}] system size
#' @param ll_system [\code{int}] level number of discrete system
#' @param sim_step [\code{int}] simulating steps
#' @param lat_type [\code{int}] lattice type
#' @param obr_window [\code{int}] observe window
#' @param obf_type [\code{char}] ordered Boolean function type
#' @param bias_rf [\code{NumericVector}] biases in random function 
#' @param obf_ratio [\code{double}] proportion of ordered Boolean function 
#' @param init_bias [\code{NumericVector}] "1" proportion of initial state 
#' @param net_type [\code{char}] system topological type
#' @param net_f_para [\code{char}] topological configured parameters
#' @param obf_i_para1 [\code{int}] configuration parameter for OBF (1)
#' @param obf_i_para2 [\code{int}] configuration parameter for OBF (2)
#' @param OutPut [\code{bool}] whehther output all states?
#' @param RuleType [\code{int}] update strategy
c_Percolation_Simualtion <- function(sys_size, ll_system, sim_step, lat_type, obr_window, obf_type, bias_rf, obf_ratio, init_bias, net_type, net_f_para, obf_i_para1, obf_i_para2, OutPut, RuleType) {
    .Call(`_BioLogical_c_Percolation_Simualtion`, sys_size, ll_system, sim_step, lat_type, obr_window, obf_type, bias_rf, obf_ratio, init_bias, net_type, net_f_para, obf_i_para1, obf_i_para2, OutPut, RuleType)
}

#' @title Analyze potential engaged nodes within Boolean/multi-valued system
#' @description C++ prototype function of \link{DNS_Engaged}
#' @param sys_size [\code{int}] system size
#' @param ll_system [\code{int}] level number of discrete system
#' @param obf_type [\code{char}] ordered Boolean function type
#' @param bias_rf [\code{NumericVector}] biases in random function 
#' @param obf_ratio [\code{double}] proportion of ordered Boolean function 
#' @param net_type [\code{char}] system topological type
#' @param net_f_para [\code{char}] topological configured parameters
#' @param obf_i_para1 [\code{int}] configuration parameter for OBF (1)
#' @param obf_i_para2 [\code{int}] configuration parameter for OBF (2)
#' @param PointedNode [\code{IntegerVector}] which nodes should be fixed
#' @param PointValues [\code{IntegerVector}] pointed values of free/controlled nodes
#' @param NodeDetailInfor [\code{bool}] should return detail informations of node
#' @param ReturnResidualNetwork [\code{bool}] should return residual networks?
c_ScalingLaw_Simualtion <- function(sys_size, ll_system, obf_type, bias_rf, obf_ratio, net_type, net_f_para, obf_i_para1, obf_i_para2, PointedNode, PointValues, NodeDetailInfor, ReturnResidualNetwork) {
    .Call(`_BioLogical_c_ScalingLaw_Simualtion`, sys_size, ll_system, obf_type, bias_rf, obf_ratio, net_type, net_f_para, obf_i_para1, obf_i_para2, PointedNode, PointValues, NodeDetailInfor, ReturnResidualNetwork)
}

#' @title Analyze core dynamic components of Boolean networks (2)
#' @description C++ prototype function of \link{BoolBioNet_CoreDyn} (\code{scaling} part). 
#' @param aRealNet [\code{List}] a real/silico genetic network (See \link{BoolGRN_CellCollective}).
#' @param PointedGene [\code{IntegerVector}] which nodes should be fixed.
#' @param PointValues [\code{IntegerVector}] pointed values of free/controlled nodes.
#' @param InD [\code{IntegerVector}] the vector of in-degrees.
#' @param OtD [\code{IntegerVector}] the vector of out-degrees.
#' @param NodeDetailInfor [\code{int}] should return detail information of node (>0, yes).
#' @param ReturnResidualNetwork [\code{int}] recursive number of analysis (>0).
c_ScalingLaw_RealNet <- function(aRealNet, PointedGene, PointValues, InD, OtD, NodeDetailInfor, ReturnResidualNetwork) {
    .Call(`_BioLogical_c_ScalingLaw_RealNet`, aRealNet, PointedGene, PointValues, InD, OtD, NodeDetailInfor, ReturnResidualNetwork)
}

#' @title Analyze core dynamic components of Boolean networks (1)
#' @description C++ prototype function of \link{BoolBioNet_CoreDyn} (\code{coredyn} part).
#' @param aRealNet [\code{List}] a real/silico genetic network (See \link{BoolGRN_CellCollective}).
#' @param PointedGene [\code{IntegerVector}] which nodes should be fixed.
#' @param PointValues [\code{IntegerVector}] pointed values of free/controlled nodes.
#' @param InD [\code{IntegerVector}] the vector of in-degrees.
#' @param OtD [\code{IntegerVector}] the vector of out-degrees.
#' @param NodeDetailInfor [\code{int}] should return detail information of node (>0, yes).
#' @param ReturnResidualNetwork [\code{int}] should return Residual Network (>0, yes).
#' @param Times [\code{int}] recursive number of analysis (>0).
c_CoreDynamicNode <- function(aRealNet, PointedGene, PointValues, InD, OtD, NodeDetailInfor, ReturnResidualNetwork, Times) {
    .Call(`_BioLogical_c_CoreDynamicNode`, aRealNet, PointedGene, PointValues, InD, OtD, NodeDetailInfor, ReturnResidualNetwork, Times)
}

#' @title Convert a Boolean function into threshold-based or polynomial forms
#' @description C++ prototype function of \link{BoolFun_Polynomial}.
#' @param VariableMat [\code{IntegerMatrix &}] a matrix of variable combination 
#' @param MapTab [\code{IntegerMatrix &}] the truth table of Boolean function.
#' @param LogiSpin [\code{int}] Should show the detail polynomial form?
c_BoolFun2Polynomial <- function(VariableMat, MapTab, LogiSpin) {
    .Call(`_BioLogical_c_BoolFun2Polynomial`, VariableMat, MapTab, LogiSpin)
}

#' @title Caluclate the network's strongly connected components
#' @description C++ prototype function of \link{BoolBioNet_StrConComp}
#' @param aRealNet [\code{List}] a real/silico genetic network (See \link{BoolGRN_CellCollective}).
#' @param InD [\code{IntegerVector}] the vector of in-degrees.
#' @param OtD [\code{IntegerVector}] the vector of out-degrees.
c_StrongConnectComponent <- function(aRealNet, InD, OtD) {
    .Call(`_BioLogical_c_StrongConnectComponent`, aRealNet, InD, OtD)
}

#' @title Calculate the complexity of a multi-valued function
#' @description C++ prototype function of \link{MulVFun_Complexity}
#' @param avec [\code{IntegerVector}] the function.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @return [\code{double}] the complexity of given function.
c_MulF_Complexity <- function(avec, k, L) {
    .Call(`_BioLogical_c_MulF_Complexity`, avec, k, L)
}

#' @title Calculate the effetive edges loading of a multi-valued function
#' @description C++ prototype function (1) of \link{MulVFun_Effectiveness}
#' @param avec [\code{IntegerVector}] the function.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @return [\code{double}] the global effetive or redundant edges of given function.
c_MulF_Effective <- function(avec, k, L) {
    .Call(`_BioLogical_c_MulF_Effective`, avec, k, L)
}

#' @title Calculate the effetive edges loading of a multi-valued function
#' @description C++ prototype function (2) of \link{MulVFun_Effectiveness}
#' @param avec [\code{IntegerVector}] the function.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @return [\code{NumericVector}] the effetive or redundant value of each edge.
c_MulF_EffectiveEdges <- function(avec, k, L) {
    .Call(`_BioLogical_c_MulF_EffectiveEdges`, avec, k, L)
}

#' @title Show the Quine-McCluskey form of a multi-valued function
#' @description C++ prototype function of \link{MulVFun_QMForm}
#' @param avec [\code{IntegerVector &}] that represents a mapping table of multi-valued function.
#' @param k [\code{int}] that denotes the number of input variables.
#' @param L [\code{int}] that represents the level of multi-valued system.
c_MulF_QuineMcCluskey <- function(avec, k, L) {
    .Call(`_BioLogical_c_MulF_QuineMcCluskey`, avec, k, L)
}

#' @title Generate a specific type of multi-valued function
#' @description C++ prototype function of \link{MulVFun_Generator}
#' @param FunType [\code{char}] function type.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @param CanaDeep [\code{int}] the layer of canalization.
#' @param CanaVar [\code{IntegerVector &}] canalized variable indexes.
#' @param CanaVarNum [\code{IntegerVector &}] the canalizing number of each variable.
#' @param CanaInfo1 [\code{List &}] canalizing information.
#' @param CanaInfo2 [\code{List &}] canalized information.
#' @param bias [\code{NumericVector &}] function bias.
#' @param Cana_Free [\code{bool}] is a parameter-free canalized function?
c_MulVF_Generator <- function(FunType, k, L, CanaDeep, CanaVar, CanaVarNum, CanaInfo1, CanaInfo2, bias, Cana_Free) {
    .Call(`_BioLogical_c_MulVF_Generator`, FunType, k, L, CanaDeep, CanaVar, CanaVarNum, CanaInfo1, CanaInfo2, bias, Cana_Free)
}

#' @title Calculate the sensitivity of a multi-valued function
#' @description C++ prototype function of \link{MulVFun_Sensitivity}
#' @param amulfun [\code{IntegerVector &}] the function.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @param Lens [\code{int}] the length of mapping table (\eqn{L^k}).
c_MulVF_Sensitivity <- function(amulfun, k, L, Lens) {
    .Call(`_BioLogical_c_MulVF_Sensitivity`, amulfun, k, L, Lens)
}

#' @title Analyze the structure of a multi-valued nested canalized function
#' @description C++ prototype function of \link{MulVFun_is_NestedCana}
#' @param amulfun [\code{IntegerVector &}] the function.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @param Lens [\code{int}] the length of mapping table (\eqn{L^k}).
c_M_NestedCanalized <- function(amulfun, k, L, Lens) {
    .Call(`_BioLogical_c_M_NestedCanalized`, amulfun, k, L, Lens)
}

#' @title Decode the information of a multi-valued linear threshold function
#' @description C++ prototype function of \link{MulVFun_is_Threshold}
#' @param amulfun [\code{IntegerVector &}] the function.
#' @param k [\code{int}] the number of input variables.
#' @param L [\code{int}] the level of function.
#' @param Lens [\code{int}] the length of mapping table (\eqn{L^k}).
c_M_Threshold <- function(amulfun, k, L, Lens) {
    .Call(`_BioLogical_c_M_Threshold`, amulfun, k, L, Lens)
}

#' @title Decode the information of a multi-valued domaineted function
#' @description C++ prototype function of \link{MulVFun_is_Domainted}
#' @param amulfun [\code{IntegerVector &}] the function.
#' @param k [\code{int}] the number of input variables of original function.
#' @param L [\code{int}] the level of original function.
#' @param Lens [\code{int}] the length of mapping table (\eqn{L^k}).
c_M_Domainted <- function(amulfun, k, L, Lens) {
    .Call(`_BioLogical_c_M_Domainted`, amulfun, k, L, Lens)
}

#' @title Decode the information of a multi-valued signed function
#' @description C++ prototype function of \link{MulVFun_is_Signed}
#' @param amulfun [\code{IntegerVector &}] the function.
#' @param k [\code{int}] the number of input variables of original function.
#' @param L [\code{int}] the level of original function.
#' @param Lens [\code{int}] the length of mapping table (\eqn{L^k}).
c_M_Signed <- function(amulfun, k, L, Lens) {
    .Call(`_BioLogical_c_M_Signed`, amulfun, k, L, Lens)
}

#' @title Convert a multi-valued function as polynomial like forms
#' @description C++ prototype function of \link{MulVFun_Polynomial}
#' @param VariableMat [\code{IntegerMatrix &}] a matrix that record input vectors.
#' @param MapTab [\code{IntegerVector &}] the function.
#' @param k [\code{int}] the number of input variables of original function.
#' @param L [\code{int}] the level of original function.
c_MulVFun2Polynomial <- function(VariableMat, MapTab, k, L) {
    .Call(`_BioLogical_c_MulVFun2Polynomial`, VariableMat, MapTab, k, L)
}

#' @title Boolean to multi-valued and multi-valued to Boolean transformation
#' @description C++ prototype function of \link{MulV2Bool_Bool2MulV}
#' @param OriMapTab, [\code{IntegerVector}] original mapping table.
#' @param k, [\code{int}] the number of input variables.
#' @param L, [\code{int}] the level of multi-valued system.
#' @param Thresholds, [\code{IntegerVector}] thresholds for a multi-valued system. 
#' @param b2m, [\code{int}] Is from Boolean to Multi-valued system? (>0, yes)
c_MulV2Bool_Bool2MulV <- function(OriMapTab, k, L, Thresholds, b2m) {
    .Call(`_BioLogical_c_MulV2Bool_Bool2MulV`, OriMapTab, k, L, Thresholds, b2m)
}

cin_OnlyTempState <- function(sys_size, ll_system, sim_step, obf_type, bias_rf, obf_ratio, init_dis, init_1_ratio, net_type, net_f_para, obf_i_para1, obf_i_para2, RuleType) {
    .Call(`_BioLogical_cin_OnlyTempState`, sys_size, ll_system, sim_step, obf_type, bias_rf, obf_ratio, init_dis, init_1_ratio, net_type, net_f_para, obf_i_para1, obf_i_para2, RuleType)
}

cin_OnlyTempState_Load <- function(aRealNet, PointedGene, PointValues, InD, OtD, init_1_ratio, sim_step, RuleType) {
    .Call(`_BioLogical_cin_OnlyTempState_Load`, aRealNet, PointedGene, PointValues, InD, OtD, init_1_ratio, sim_step, RuleType)
}

c_ObtainFeedBackLoop <- function(aRealNet, InD, OtD, Isolated, Type) {
    .Call(`_BioLogical_c_ObtainFeedBackLoop`, aRealNet, InD, OtD, Isolated, Type)
}

c_AttractorSim <- function(aRealNet, SimNum, PointedGene, PointValues, InD, OtD, sim_step, RuleType, L_sys) {
    .Call(`_BioLogical_c_AttractorSim`, aRealNet, SimNum, PointedGene, PointValues, InD, OtD, sim_step, RuleType, L_sys)
}

c_AttractorSim_MulVal <- function(aRealNet_MulVal, SimNum, PointedGene, PointValues, InD, OtD, AllNegative, sim_step, L_sys) {
    .Call(`_BioLogical_c_AttractorSim_MulVal`, aRealNet_MulVal, SimNum, PointedGene, PointValues, InD, OtD, AllNegative, sim_step, L_sys)
}

